name: jupyter-nb

services:
  notebook:
    #image: docker.io/jupyter/tensorflow-notebook
    build: ./
    environment:
      - JUPYTER_TOKEN=iambatman
      - NB_USER=${USER}
      - CHOWN_HOME=yes
      - CHOWN_EXTRA=/home/jovyan/
      - CHOWN_EXTRA_OPTS=-R
    volumes:
      - ${PWD}/work/:/home/jovyan/
    working_dir: /home/jovyan/
    ports:
      - 8080:8888
