name: jupyter-nb

services:
  notebook:
    #image: docker.io/jupyter/tensorflow-notebook
    build: ./
    environment:
      - JUPYTER_TOKEN=iambatman
      - NB_USER=${USER}
      - CHOWN_HOME=yes
      - NB_UID=${UID}
      - NB_GID=${GID}
      # - JUPYTER_RUNTIME_DIR=/tmp/jupyter-runtime
      # - CHOWN_EXTRA="${PWD}"
      # - CHOWN_EXTRA_OPTS="-R"
    volumes:
      - ${PWD}/work/:/home/jovyan/work
    working_dir: /home/jovyan
    ports:
      - 8080:8888
